### ISSUE TITLE
i found issue when trying to compile the object file, i dont what to do....HELP

### ISSUE THREAD

**Issue by outerVoid** [outerVoid/cuddly-guacamolesiiks#1]
`#include <stdio.h>
#include <iostream>
#include <fstream>

using namespace std;
class troad
{
public:
float Length;
int Width;
troad();
troad(float Length0,int Width0);
void fileinput();
};

troad::troad()
{
Length=0.0;
Width=0;
}

troad::troad(float Length0,int Width0)
{
if(Length0>0)Length=Length0;else Length=1;
if(Width0>0)Width=Width0;else Width=1;
}

void troad::fileinput()
{
char buff[50];
char buff1[50];
ifstream fin("file.txt");
fin>>buff;Length=atof(buff);
fin>>buff1;Width=atoi(buff1); 
}

int main()
{
troad road;
std::cout<<"road.Length = "<<road.Length<<"\nroad.Width = "<<road.Width<<std::endl;
troad.fileinput();
std::cout<<"file.Length = "<<fileinput.Length<<"\nfile.Width = "<<fileinput.Width<<std::endl;
return 0;
}
`
![default](https://user-images.githubusercontent.com/46788102/51376699-617e0e80-1b22-11e9-990c-6a010ce31e0c.png)

**Comment by Vladosetskii** [comment]
Не понимаю пиздец сложно сори бро

**Comment by Vladosetskii** [comment]
Оставим это гениям

**Comment by Vladosetskii** [comment]
Или геям

**Comment by outerVoid** [comment]
ohohoh, i know what the problem....now i know how to fix this problem/bug!
`int main()
{
troad road;
std::cout<<"road.Length = "<<road.Length<<"\nroad.Width = "<<road.Width<<std::endl;
road.fileinput();
std::cout<<"file.Length = "<<road.Length<<"\nfile.Width = "<<road.Width<<std::endl;
return 0;
}`
#

**Comment by outerVoid** [comment]
i found decision about this problem/bug! Thanks all!
